services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./comprovantes:/app/comprovantes

